create table rp_product_hist_ds.rp_product_hist_table(
	CUST_ID INT64,
	USR_COUNT INT64,
	ORD_ID INT64,
	PURCH_DATE DATE,
	REC_DATE DATE,
	PRICE_ITEM FLOAT64,
	QTY INT64,
	CUST_AMT FLOAT64,
	REC_QTY INT64,
	REC_AMT FLOAT64,
	web_prod_id INT64,
	GMM_DESC STRING,
	PARENT_MDSE_DIVN_DESC STRING,
	LOAD_DT TIMESTAMP,
	COUNTRY_CODE STRING,
	ENTITY_CODE STRING
);
